name: Build Android APK

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4

    - name: Build APK from URL
      uses: jonasmerlin/web-to-apk-action@v1
      with:
        # رابط موقعك على نيتليفاي
        url: https://fluffy-taffy-3bdf81.netlify.app/
        # الاسم الذي تريده للتطبيق على شاشة الهاتف
        name: My Netlify App
