name: Build Android APK

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4

    - name: Build Android APK
      uses: nim901/pwa-to-apk-action@v1
      with:
        # رابط موقعك على نيتليفاي
        url: 'https://fluffy-taffy-3bdf81.netlify.app/'
        # اسم التطبيق
        name: 'My Netlify App'
